### ISSUE TITLE
absolute paths in run-version-genprog.sh

### ISSUE THREAD

**Issue by aar-gee** [codeflaws/codeflaws#1]
Hi,

I am trying to run genprog on the benchmarks provided. There are some absolute paths in run-version-genprog.sh file (and may be other files as well). I'm not able to figure out which file is required here?

`filename="$rootdir/run1" #previous defect-movestatement`

Could you please explain?

**Comment by stan6** [comment]
Hi Rahul, thank you for your interest in Codeflaws.

The comment in each script explained how you should change the value for $rootdir. For example, rootdir="/home/ubuntu/codeforces-crawler/CodeforcesSpider" #directory of this script. So, the $rootdir should be set to the same directory (let say it is "dirA") in which the script "run-version-genprog.sh" is located and it assume that the codeflaws.tar.gz will be untar in the same directory where you have dirA/codeflaws. Another directory you will need to change is the location of the repair tool. For example, in run-version-genprog.sh, genprog="/home/ubuntu/genprog-source-v3.0/src/repair", you will need to point it to the location in which you have installed genprog.  

The "filename" variable specify the versions in codeflaws you would like to run. You can change the filename="$rootdir/run1" to be filename="$rootdir/codeflaws-defect-detail-info.txt".  If you only want to run several versions in codeflaws, you can have a shorten version of the "codeflaws-defect-detail-info.txt" file.

Below are the commands you will need to create the setup assumming that you would like to have everything under dirA:
cd dirA
wget http://www.comp.nus.edu.sg/%7Erelease/codeflaws/codeflaws.tar.gz
tar xzvf codeflaws.tar.gz
mkdir genprog-run #this is the temporary directory in which different program versions will be copied. 
#modify genprog="/home/ubuntu/genprog-source-v3.0/src/repair" and rootdir="/home/ubuntu/codeforces-crawler/CodeforcesSpider"
#modify filename="$rootdir/run1"
After that, you should be able to run ./run-version-genprog.sh
