### ISSUE TITLE
Programing Problem Description

### ISSUE THREAD

**Issue by BEbillionaireUSD** [codeflaws/codeflaws#12]
Thanks for your dataset. 
May I know how to get the corresponding original problem descriptions (written in natural languages)?

**Comment by mechtaev** [comment]
Hi, each problem is labelled with the problem ID. You can find its natural langauge description on Codeforces website. For example, 71-A is here: https://codeforces.com/problemset/problem/71/A?locale=en

**Comment by BEbillionaireUSD** [comment]
Thanks for your reply. I understand that I have to crawl the descriptions.
