### ISSUE TITLE
Python modules import error

### ISSUE THREAD

**Issue by yodahaji** [codeflaws/codeflaws#3]
when i run code-build.py,it tells there is no module named tester_common,which is in the 4th line of this file.how can i solve it?

**Comment by yodahaji** [comment]
i also googled python tester_common module,but nothing found.

**Comment by stan6** [comment]
Hi yodahaji, thanks for your interest in codeflaws. 

I have uploaded the tester_common.py in codeflaws/allscript/ as requested. I didn't include the file originally because the file is part of Prophet (in prophet-gpl/tools/tester_common.py).

**Comment by yodahaji** [comment]
thanks for your quickly reply:D.
and there is still a same question :when i try to run the run-test.py,it it will tell that there is  no module named pexpert.i think it is the same reason.

and if possiple,could you just make a simple tutorial about how to use codeflaw to repair the C code? i've readed your papers and readme in the github,but still struggle to do so.

**Comment by stan6** [comment]
Hi yodahaji, you can install pexpect using:
> pip install pexpect
Or:
> easy_install

As your question is related to installation of the repair tool itself, it is beyond the scope of codeflaws. 

After installing prophet, you can prepare a version-to-run containing all or part of "all-script/codeflaws-defect-detail-info.txt", change the following variables in the run-version-prophet.sh and then you should be able to run prophet:
rootdir="/home/ubuntu/codeforces-crawler/CodeforcesSpider" #directory of this script
rundir="$rootdir/prophet-run" # directory in which prophet is called from
versiondir="$rootdir/codeflaws" #root directory for the codeflaws versions
filename="$rootdir/run1" #tab-separated file containing the list of versions to run as the first field (the version-to-run file),
prophet="/home/ubuntu/spr/src/prophet" # location of the prophet executable
rundir="$rootdir/prophet-run"

**Comment by yodahaji** [comment]
So you mean i should first install the 4 repair tool .only after it,i can use it with codefalw:benchmarck?

and there is another problem,the run-test.py and the code-build.py still can not be compiled succesfully.the python version i use is 2.7. when i compile run-test.py,it shows:
 NameError: name 'currdir' is not defined

and when it is code-build.py,it diagnostics as 
cannot find makefile

the make file is in the codeflaws folder of each subfolder i know,so should i add the path of one of the subfolders?or it should run after i install the repair tools? 

the last question is compile.pl,it hints me to add a path as argument,and i try the every path in the folder,which contains all-script and the benchmark. should it run after the repair tools been installed,and add the repair tool as the path argument?

thanks for a lot for your patiently answering:D

**Comment by stan6** [comment]
> So you mean i should first install the 4 repair tool .only after it,i can use it with codeflaw:benchmarck?
You don't need to install all 4 repair tools if you don't need them. If you are interested in a particular repair tool, you could install that tool, and run it with corresponding run-version-<tool>.sh.

The python script doesn't need to be compiled, you get the error because the run-test.py requires the following parameters:
src_dir = args[0];
test_dir = args[1];
work_dir = args[2];

Both run-test.py and code-build.py are used internally by the repair tools. The run-version-prophet.sh script will setup all the required parameters for running both python scripts.  If you want to compile or test individual version without running repair tools, you can simply use the following:

> cd $version-dir

> make #compile a version

> ./test.sh n1 #run test, n1 denotes the negative test, p1...pn denote positive tests.

**Comment by yodahaji** [comment]
thank you very much!!!
