### ISSUE TITLE
How should i use the benchmark with the 4 repair tools?

### ISSUE THREAD

**Issue by yodahaji** [codeflaws/codeflaws#4]
sorry for my foolishment. i am confused about this for days. i tried many methods but stiil cant make the repair tools work with the benchmark.
could you tell me ,if i have installed  genprog in another folder different from this folder wich contains the all-script and codeflaws. Then what should i do to make genprog run with the codeflaw? i know there is compile.pl and run-version-genprog.sh and  validate-fix-genprog.sh for genprog. but what should i do ?
should i run one of them? i tried all of them ,but every time it all fails.
when i run compile.pl ,it will asks one argument as folder,i have tested every folder include:the codeflaws, the all-script, the . , the .. , and i also tried the root and the src folder of the genprog, but all fails. even when i choose the root of the genprog as the argument,it seems to walk throuth the all disks in my computer. 
and when i run-version-genprog.sh , it would hint thar there is no file named run1, when i see the script, i find it means the previous defect-movestatement,but what's that exactly? and the other lines in the top of this script also confused me .
then,when i run validate-fix-genprog.sh ,it seems like dive into a forever loop and never return.

could you tell me what i should do exactly to make this benchmark work with the repair tools?

**Comment by stan6** [comment]
You should run run-version-genprog.sh.
 
All the following variables defined in the first few lines of run-version-genprog.sh should be modified to reflect the correct path:

rootdir="/home/ubuntu/codeforces-crawler/CodeforcesSpider" #directory of this script
rundir="$rootdir/genprog-run" # directory in which genprog is called from, a temporary output directory where everything will be copied to during the repair
versiondir="$rootdir/codeflaws" #directory where the codeflaws.tar.gz is extracted
filename="$rootdir/run1" #should be a copy of the codeflaws-defect-detail-info.txt
genprog="/home/ubuntu/genprog-source-v3.0/src/repair"
The run1 file needs to be created manually. The file could be an exact copy of the "codeflaws-defect-detail-info.txt" file where each line denotes a particular defect or you could copy first few line to run only several defects to test the script.

**Comment by yodahaji** [comment]
hi,the method you said works well,it can run now.
but do i need to run compile.pl first? because after i set the first few lines of run-version-genprog.sh, and i delete the lines to 10. however it will hint (it is translated by me,because the system is not english system)
can not get the stat of '71-A-18359456.cil.c' ,the file or the directory is not exist .
can not get the stat of 'preprocessed/71-A-18359456.c' ,the file or the directory is not exist .
RUNNING CMD:/mnt/f/genprog-code-snapshot/src/repair configuration-71-A-bug-18359456-18359477
./run-version-genprog.sh: line 124:  1608 segment fault     timeout -k 3600s 3600s $genprog configuration-$version &> $rundir/temp-$version.out 
...
all the ten samples are the same case.did i do anything wrong?

**Comment by droix2017** [comment]
Hi, I am glad to know that the instructions work well for you.

You don't need to run compile.pl.

I am not sure whether this is the cause of the error but the error message seems to indicate that the "cilly" compiler of GenProg is not in the path. Did you build GenProg and cilly succesfully? As far I can remember, cilly should be in genprog-dir/cil-1.7.3/bin/cilly. If you didn't find it, you can also download it at [https://github.com/cil-project/cil/releases](https://github.com/cil-project/cil/releases). You will need to add the path of cilly: 
export PATH=$PATH:<path-to-cilly>

**Comment by stan6** [comment]
Hi, I am glad to know that the instructions work well for you.

You don't need to run compile.pl.

I am not sure whether this is the cause of the error but the error message seems to indicate that the "cilly" compiler of GenProg is not in the path. Did you build GenProg and cilly succesfully? As far I can remember, cilly should be in genprog-dir/cil-1.7.3/bin/cilly. If you didn't find it, you can also download it at https://github.com/cil-project/cil/releases. You will need to add the path of cilly:
export PATH=$PATH:

**Comment by yodahaji** [comment]
Oh,it have been run for about 2hours in the first line of the codeflaws-defect-detail-info.txt,i dont know wether this is normal,but it still doesnt give any message(error message or whatever) now.In other way,it seems work very well now.

a small suggestion is to write more about how to use this benchmark with the auto-repair-tool to the Readme,i believe this will give more help to others:D

Sincerely Thanks to You.

**Comment by stan6** [comment]
Thanks for the feedback. As requested, I have added more descriptions to the README.md and all other run-version-<repair-tool>.sh file.

The current timeout for one defect is one hour. Together with the initial compilation time, the running time for one particular defect should not be 2 hours. 

You could check $rundir/temp-$version.out to see the logfile for a particular version ($version is printed as "RUNNING CMD:$genprog configuration-<$version>").

**Comment by yodahaji** [comment]
Yeah,you are right.Although the command line doesn't give any message,all ten $version.out file are made successfully.

and there is only 3 things i concerned in the every $version.out . 
The first is near the bottom of the file,it prints:

cat: /etc/redhat-release: there is not the file or directory
cat /etc/redhat-release: End_of_file

but my OS is not redhat,it is ubuntu.i think it may be the problem of the genprog,not the codeflaw,because codeflaw is not driver.

the second is in the last line of the file,it shows:

timeout: the monitored command dumped core

it should be my problem, because the comand line dosent move at all. and i now are trying to make another try to run this script to see what would happen. 

and the last is the most question i want to ask: e.g., now i have the codeflaw benchmark  and the genprog, when i want to combine this two,i need to run ./run-version-genprog.sh, and the programs to be run is in the copy of codeflaws-defect-detail-info.txt.but if i want to use the two tools to auto repair another code,what should i do? need i put this code , the positive tests , the negative tests, test script  ,and anything without the right code ,in one directory,and put it in the codeflaws.then i add the directory name to the copy of codeflaws-defect-detail-info.txt. after that,when i run the  ./run-version-genprog.sh,would i get the (maybe) right code? it does not ressemble a right method.

so what should i do to make this, combine benchmark and e.g., genprog together, to auto repair the code i want? Or it doesnot support this feature?

i'm sorry if i troubled you.

**Comment by stan6** [comment]
Thank you for spending time in running codeflaws.


> cat: /etc/redhat-release: there is not the file or directory
> cat /etc/redhat-release: End_of_file

Yes, this is the output of genprog but you could safely ignore this as it doesn't affect its ability to generate patches.

>timeout: the monitored command dumped core

this may occur when genprog doesn't find any patch within the timeout of 1 hour. On a related note, this reminds me that you need to ensure that the time command is installed in order for the test cases in codeflaws to run correctly: 
```
sudo apt-get install time
```

> e.g.,now i have the codeflaw benchmark and the genprog, when i want to combine this two,i need to 
> run./run-version-genprog.sh, and the programs to be run is in the copy of codeflaws-defect-detail-info.txt.but if i want to use the two tools to auto repair another code,what should i do?

Codeflaws is a benchmark and genprog is a repair tool. When you are running ./run-version-genprog.sh, you are essentially using genprog to repair the subject programs in Codeflaws. For repairing other programs beyond Codeflaws, you could not use run-version-genprog.sh directly.

> need i put this code , the positive tests , the negative tests, test script ,and anything without the right 
> code, in one directory,and put it in the codeflaws.then i add the directory name to the copy of 
> codeflaws-defect-detail-info.txt.after that,when i run the ./run-version-genprog.sh,would i get the (maybe) right code? 

I don't think you will get the right code even when you put all the required files under the correct directory but you could use the run-version-genprog.sh script, compile.pl, test.sh as guidance to learn about how to prepare a subject program  for a given repair tool (e.g., genprog). In fact, running genprog only require running the following command:
```genprog configuration-file```
All other codes in run-version-genprog.sh helps you setup the parameter for the configuration-file correctly. Another caveat is that GenProg requires files to be compiled with cilly to produce *.cil.c files and this conversion seems to causes compilation errors for some bigger programs. 

> so what should i do to make this, combine benchmark and e.g., genprog together, to auto repair the 
> code i want? Or it doesnot support this feature?

Sorry, running programs beyond defects in Codeflaws is not supported as this is outside the scope of our benchmark. But for simple programs with one file, you should be able to reuse the structure of "compile.pl" and "test.sh" and modify run-version-genprog.sh accordingly.

**Comment by yodahaji** [comment]
Thanks for concrete explaintion .

Now i know the benchmark is a tool to test wether the repair tools works correctly,isn't it?

And a small problem is yesterday i ,said that there is ten  $version.out in the directory,but i doubt that all of them are the production of the previous tests.so i delete all of them ,and run ./run-version-genprog.sh again.After all night,the command line still keep in the 
Diff Cases 1:1
and the files that should be in that directory are not there without a directory: tempworkdir-71-A-bug-18359456-18359477, which should be the first test case.And there is no $version.out now.

Does it means my genprog haven't been installed correctly or other reasons?

**Comment by stan6** [comment]
> Now i know the benchmark is a tool to test wether the repair tools works correctly,isn't it?

Yes, the benchmark is to evaluate repair tool. If a new repair tool is designed, it can be ran easily with Codeflaws to compare its performance with other existing repair tools.  

> Does it means my genprog haven't been installed correctly or other reasons?
Sorry, your previous run seems to be correct but I am not sure what are the exact changes you made after the run. I guess there may be many possibilities: 
1. You accidentally specific the output directory "$rundir" the same as "versiondir", Note that the $versiondir is the original directory where the codeflaws.tar.gz is extracted but $rundir is only temporary directory which will be removed by the run-version-genprog.sh script for each run to remove old results. To solve this problem, you need to change the $rundir.
2. You accidentally delete $versiondir where the codeflaws.tar.gz is extracted to. This directory should have the original copy of all defects (including $versiondir/71-A-bug-18359456-18359477 directory). For each run, run-version-genprog.sh will copy a directory to $rundir/tempworkdir-<$version> to prepare a defect for running.   To solve this problem, you need to download the codeflaws.tar.gz again.
3. You forget to set cilly again. Note that if you need to do export PATH=$PATH:<cilly> if you use a new terminal/shell. You can also include it in ~/.bashrc to avoid calling export everytime.
4. You can also check if configuration-71-A-bug-18359456-18359477 is similar to codeflaws/all-script/
configuration-default. It is possible that you deleted configuration-default accidentally as well. In this case, you need to restore all files in the the codeflaws/all-script/. 

As I have mentioned previously, if you want to check if genprog is installed correctly, you can always run (assume genprog is installed in "/home/ubuntu/genprog-source-v3.0/") genprog directly:
```/home/ubuntu/genprog-source-v3.0/src/repair configuration-71-A-bug-18359456-18359477```

**Comment by yodahaji** [comment]
i checked the 4 things you point out.and i do not do these things.

i have tried the run-version-genprog.sh  for times. it's still the same case:it will still stop at the first case.and the output files in the  $rundir don't appear. 

i also checked if i installed genprog correctly as you mentioned.

it prints the message as below:

> WARNING: the argument --multi-file is deprecated. This is not fatal, as GenProg can handle certain deprecated options as of the March 2012 refactor.
However, you may want to consult the GenProg documentation to avoid using
deprecated options in the future, and verify that your config is doing what you
think it is doing.
WARNING: the argument --suffix-extension is deprecated. This is not fatal, as GenProg can handle certain deprecated options as of the March 2012 refactor.
However, you may want to consult the GenProg documentation to avoid using
deprecated options in the future, and verify that your config is doing what you
think it is doing.
WARNING: the argument --mutp is deprecated. This is not fatal, as GenProg can handle certain deprecated options as of the March 2012 refactor.
However, you may want to consult the GenProg documentation to avoid using
deprecated options in the future, and verify that your config is doing what you
think it is doing.
GenProg Version: 2017.9.15 friday 17:54:39 DST

--allow-coverage-fail false
--appp 0.33333
--asm-code-only false
--best-edit-rule "1 * fault_loc_weight ; 1 * max_test_fail_prob ; -1 * num_tests"
--best-test-rule "1 * test_fail_prob ; 1 * test_fail_count ; -1 * test_pass_count"
--clone-file ""
--compiler "gcc"
--compiler-command "perl compile.pl __EXE_NAME__ > build.log"
--compiler-opts ""
--continue false
--coverage-info ""
--coverage-per-test false
--crossover "subset"
--crossp 0.5
--delp 0.33333
--describe-machine true
--diversity-selection 0
--edit-script false
--elf-risc false
--eviction-strategy "random"
--exclude-edits ""
--exp-diff false
--fault-file ""
--fault-path "coverage.path.neg"
--fault-scheme "path"
--fitness-in-parallel 1
--fitness-log ""
--fix-file ""
--fix-oracle ""
--fix-path "coverage.path.pos"
--fix-scheme "default"
--flatten-path "last"
--format "txt"
--gen-per-exchange 1
--generations 10
--geomp 0.5
--gui false
--hostname "127.0.0.1"
--ignore-dead-code false
--ignore-equiv-appends false
--ignore-standard-headers false
--ignore-string-equiv-fixes false
--ignore-untyped-returns false
--incoming-pop ""
--keep-source false
--label-repair true
--lase-deallocation-api "free"
--lase-paired-functions ""
--lasep 0
--max-evals 0
--minimization false
--mt-cov false
--multiopt-minimize false
--multiopt-no-inf false
--neg-tests 1
--neg-weight 1
--negative-test-weight 2
--nested false
--neutral-walk-max-size 0
--neutral-walk-weight ""
--nht-id "global"
--nht-port 51000
--nht-server ""
--no-rep-cache true
--no-test-cache true
--num-comps 2
--num-objectives 2
--oracle-genome ""
--pd-mutp 0.25
--popsize 40
--port 60000
--pos-tests 1
--pos-weight 0.1
--prefix "preprocessed"
--preprocessor ""
--print-incremental-evals false
--print-source-name false
--program "bugged-program.txt"
--promut 1
--quiet false
--regen-paths false
--rep "cilpatch"
--rep-cache "default.cache"
--repp 0
--samp-strat "variant"
--sample 1
--sample-runs 100
--sanity "yes"
--search "ww"
--seed 0
--semantic-check "exact"
--single-fitness false
--skip-failed-sanity-tests false
--skip-tests ""
--split-search 0
--sport 65000
--subatom-constp 0.5
--subatom-mutp 0
--swap-bug false
--swapp 0.33333
--template-cache ""
--templates ""
--test-command "timeout -k 50s 50s __TEST_SCRIPT__ __TEST_NAME__ >/dev/null"
--test-script "./test-genprog.sh"
--tournament-size 2
--uniq false
--use-partition -1
--valgrind false
--variants-exchanged 50
--version false
uname -a: Linux LegendNoComputer2 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
date: 2017年 09月 16日 星期六 20:13:56 DST
id: uid=1000(legend-k) gid=1000(legend-k) 组=1000(legend-k),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev)
cat: /etc/redhat-release: 没有那个文件或目录
cat /etc/redhat-release: End_of_file
grep model name /proc/cpuinfo: model name       : Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
grep MemTotal /proc/meminfo: MemTotal:        8269444 kB
grep SwapTotal /proc/meminfo: SwapTotal:      16463484 kB
cilRep: preprocessing IO function signatures: /tmp/tmp4ddb46.c /tmp/tmp4a3cf0.c
segment fault


and it seems to be the cause of the problem. do i need to reinstall genprog again? or any others?

and there is another question as  you mentioned the benchmark is to evaluate the repair tools.but where is the result of the evaluation? or it's because i didn't do the right things?

**Comment by stan6** [comment]
> i checked the 4 things you point out.and i do not do these things.

Sorry, in this case, I couldn't help you to figure out the reason for this behavior then. Not sure if it is because it is stuck at the first defect. Maybe you remove this defect (the first line in your run1 file) and let it run for other defects to see if other defects is run correctly?

> and it seems to be the cause of the problem. do i need to reinstall genprog again? or any others?

The message seems to indicate that you didn't run it for the correct file(tmp4a3cf0.c seems to be an unknown file). The configuration-configuration-71-A-bug-18359456-18359477 should be run inside the tempworkdir-71-A-bug-18359456-18359477. In the tempworkdir-71-A-bug-18359456-18359477, you should be able to find a file called bugged-program.txt with one line "71-A-18359456.c" that mentioned about the buggy file that you are repairing.


> and there is another question as you mentioned the benchmark is to evaluate the repair tools.but where is the result of the evaluation? or it's because i didn't do the right things?

The results of the evaluation is the number of patches that it generates and you can use validate-fix-genprog.sh to check for each generated repair if it is correct.

**Comment by BesmaKH** [comment]
Hi did you find a solution to seg fault while installing genprog i'm facing the same issue
