### ISSUE TITLE
Crawler

### ISSUE THREAD

**Issue by ppashakhanloo** [codeflaws/codeflaws#7]
Hello

I was wondering if the crawler you used is available.
I read in your paper that you modified https://github.com/Nymphet/codeforces-crawler to suit the purpose of the codeflaws benchmark. I was not able to find it under this repository. Is it available?

Thanks

**Comment by stan6** [comment]
Hi, thanks for the question. Unfortunately, we lost the code for the crawler so we did not made it available.
